application: yowatariapp
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on
- remote_api: on
# - appstats: on
# python25じゃないと動かない＞＜
# - datastore_admin: on

handlers:
- url: /static/images
  static_dir: static/images
  expiration: "7d"

- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /_ah/queue/deferred
  script: process.app
  login: admin

- url: /cron/task/friendlist
  script: process.app
  login: admin

- url: /cron/task/items
  script: process.app
  login: admin

- url: .*
  script: main.app

libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
- name: lxml
  version: latest
